### ISSUE TITLE
rustup toolchain install nightly doesn't expect `-y` argument

### ISSUE THREAD

**Issue by EverlastingBugstopper** [CircleCI-Public/rust-orb#15]
## Orb version:

`circleci/rust@1.5.0`

## Project Info:

During my test workflow, I am invoking `rust/install` on the base CircleCI image (`cimg/base:stable`) like so:

```
jobs:
  xtask:
    parameters:
      rust_channel:
        type: enum
        enum: ["stable", "nightly"]
        default: stable

... other info omitted ...

  steps:
    - rust/install:
        version: << parameters.rust_channel >>
``` 

Then, in my test workflow, I have the following matrix:

```yaml
workflows:
  test:
    jobs:
      - xtask:
          matrix:
            parameters:
              platform: [ubuntu_gnu, ubuntu_musl, macos]
              rust_channel: [stable, nightly]
              command: [test]
```

## Expected behavior:

Ideally, this would install the proper rust toolchain

## What Happened

`stable` installs work fine, but `nightly` installs fail with the following error:

```
error: Found argument '-y' which wasn't expected, or isn't valid in this context

USAGE:
    rustup toolchain install [FLAGS] [OPTIONS] <toolchain>...
```

---

I believe this is due to the following code:

```bash
#!/bin/bash -eo pipefail
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
chmod +x rustup.sh
./rustup.sh -y

source "$HOME"/.cargo/env

if [ "$RUST_VERSION" != "stable" ]; then
	rustup toolchain install "$RUST_VERSION" -y
	rustup default "$RUST_VERSION" -y
fi
```

Simply removing the `-y` parameters for `toolchain install` and `default` should fix this, like so:

```bash
#!/bin/bash -eo pipefail
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
chmod +x rustup.sh
./rustup.sh -y

source "$HOME"/.cargo/env

if [ "$RUST_VERSION" != "stable" ]; then
	rustup toolchain install "$RUST_VERSION"
	rustup default "$RUST_VERSION"
fi
```
