### ISSUE TITLE
`rust/build` command fails to compute hash if `Cargo.lock` not in the root

### ISSUE THREAD

**Issue by citizen-stig** [CircleCI-Public/rust-orb#17]
## Orb version:

1.5.0

## What happened:

When rust project is located in sub-folder, `rust/build` command fails to compute hash
```
      - rust/build:
          working_directory: ~/sub-folder
          release: true
```

Error is:

```
error calling checksum: open /home/circleci/project/Cargo.lock: no such file or directory
```

## Expected behavior:

Job builds rust project inside `working_directory`

## Additional Information:

Based on source of orb command:

```
  - when:
      condition: <<parameters.with_cache>>
      steps:
        - restore_cache:
            keys:
              - 'cargo-<<parameters.cache_version>>-{{ checksum "Cargo.lock" }}'
```

Checksum requires `Cargo.lock` to be present in root folder
