### ISSUE TITLE
change the rust/install restup profile to minimal

### ISSUE THREAD

**Issue by evant** [CircleCI-Public/rust-orb#21]
## Describe Request:

On ci you may want to save some download time by not installing all the rust components, especially if you don't need them. You can manage profiles to do this. This could either be done by default by passing `--profile minimal` or by giving an additional option to set it.

## Examples:

An option could look like:
```yaml
- rust/install:
      version: 1.72.0
      profile: minimal
```

## Supporting Documentation Links:
https://rust-lang.github.io/rustup/concepts/profiles.html
