### ISSUE TITLE
rust/format defaults to nightly

### ISSUE THREAD

**Issue by bergmark** [CircleCI-Public/rust-orb#24]
## What happened:

A minimal workflow running `rust/format` fails with `error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed`. Note that `nightly-toolchain` is not set and defaults to false.

config:.yml:
```
version: 2.1
orbs:
  rust: circleci/rust@1.6.1

jobs:
  orb-format:
    docker:
      - image: cimg/rust:1.74.1
    steps:
      - checkout
      - rust/format

workflows:
  example:
    jobs:
      - orb-format
```

## Expected behavior:

This should run format using the installed stable version of rust.

## Additional Information:

I'm new to circleci but based on some debugging it seems like the culprit is
```
                    if [ "$ORB_VAL_NIGHTLY_TOOLCHAIN" ]; then
                        rustup_args+=(--toolchain nightly)
                        cargo_args+=(+nightly)
                    fi
```
where `$ORB_VAL_NIGHTLY_TOOLCHAIN` is based on a `boolean` parameter which defaults to `false`. That gets converted to `0` in bash, and that coerces to `true` in the conditional.

As far as i can tell there is no workaround to this as providing no value, true, or false, will all cause this branch to run.
