### ISSUE TITLE
`CARGO_HOME` should be read, f.e. when using the official Rust image

### ISSUE THREAD

**Issue by gdubicki** [CircleCI-Public/rust-orb#26]
## Orb version:

v1.6.1

## What happened:

I used the latest stable official Rust image from DockerHub for building.

My cache was empty because the orb was assuming that it was always under `~/.cargo` while this image sets `CARGO_HOME` to `/usr/local/cargo`.

I had to override the `CARGO_HOME` for caching to work:
```yaml
jobs:
  test:
    working_directory: ~/foo-service
    docker:
      - image: rust:1.78.0-bullseye
    environment:
      CARGO_HOME: /root/.cargo
    steps:
      - # ...
      - rust/test:
          working_directory: ~/foo-service
          cache_version: v2
```
## Expected behavior:

The orb should check if `CARGO_HOME` is set and if so, read the cargo workdir from it.

## Additional Information:

I don't know why the `CARGO_HOME` is overridden in that image. Maybe there is a good reason and something else will break when I change it again to `/root/.cargo`?
