### ISSUE TITLE
Computing cache key fails if `Cargo.lock` is not located in the project root

### ISSUE THREAD

**Issue by brozansk** [CircleCI-Public/rust-orb#6]
## Orb version:

1.1.0

## What happened:

The error I get:
>error computing cache key: template: cacheKey:1:9: executing "cacheKey" at <checksum "Cargo.lock">: error calling checksum: open /home/circleci/project/Cargo.lock: no such file or directory

I have a project structure like:

```
.
<some other files>
└── tools
        └── my-rust-tool
                ├── Cargo.lock
                ├── Cargo.toml
                └── src
```
I provide the `working_directory` parameter `~/project/tools/my-rust-tool` in workflows. My config.yml looks like:
```yaml
version: 2.1
orbs:
  rust: circleci/rust@1.1.0
workflows:
  pr:
    jobs:
     - rust/lint-test-build:
          with_cache: true
          working_directory: ~/project/tools/my-rust-tool
```

## Expected behavior:

The cache key should use the provided `working_directory` to locate Cargo.lock file.

## Additional Information:

I believe, that the issue is here:
https://github.com/CircleCI-Public/rust-orb/blob/3579d647619e2a7afad31191a999bfce4d10f810/src/jobs/lint-test-build.yml#L41-L42
https://github.com/CircleCI-Public/rust-orb/blob/3579d647619e2a7afad31191a999bfce4d10f810/src/jobs/lint-test-build.yml#L60

as well as in cache related parts in each command code.
